# Generated by Django 3.2.2 on 2021-05-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('question_type', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('analyze', models.CharField(blank=True, max_length=255, null=True)),
                ('retail_credit_department', models.CharField(blank=True, max_length=100, null=True)),
                ('corporate_credit_department', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_service', models.CharField(blank=True, max_length=100, null=True)),
                ('marketing_department', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_public_relations_department', models.CharField(blank=True, max_length=100, null=True)),
                ('the_brand_sales_department', models.CharField(blank=True, max_length=100, null=True)),
                ('multi_brand_sales_department', models.CharField(blank=True, db_column='multi-brand_sales_department', max_length=100, null=True)),
                ('used_car_business_department', models.CharField(blank=True, max_length=100, null=True)),
                ('technology_business_department', models.CharField(blank=True, max_length=100, null=True)),
                ('big_data_platform_department', models.CharField(blank=True, max_length=100, null=True)),
                ('ministry_of_science_and_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_management_department', models.CharField(blank=True, max_length=100, null=True)),
                ('financial_accounting_department', models.CharField(blank=True, max_length=100, null=True)),
                ('integrated_management_department', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_management_department', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_audit_section', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_compliance_department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
    ]
